key: debag
experiment_name: debag

## -------datasets (HeteroGraph)----
HeteroGraph: &HeteroGraph
 seeds: 1
 gpu: 0
 cpu: False
 root: ../data/

# -------datasets (HGB)-------------
DBLP: &DBLP
  <<: *HeteroGraph
  dataset: DBLP
  nclass: 4
  tgt_type: A

ACM: &ACM
  <<: *HeteroGraph
  dataset: ACM
  nclass: 3
  tgt_type: P
  ACM_keep_F: False

IMDB: &IMDB
  <<: *HeteroGraph
  dataset: IMDB
  nclass: 5
  tgt_type: M
  
Freebase: &Freebase
  <<: *HeteroGraph
  dataset: Freebase
  nclass: 7
  tgt_type: '0'

# -------model instance------------
SeHGNN: &SeHGNN
  embed_size: 256
  label_feats: False
  num_label_hops: 2
  n_fp_layers: 2
  n_fp_submetapath_layers: 2
  n_task_layers: 3
  hidden: 512
  dropout: 0.5
  input_drop: 0.1
  att_drop: 0.
  act: none # ['none', 'relu', 'leaky_relu', 'sigmoid']
  residual: False
  amp: False
  lr: 0.001
  weight_decay: 0
  batch_size: 10000
  patience: 50
  num_heads: 1
  neighbor_aggr_mode: use_submetapath_for_semantic_fusion
  submetapath_feature_weight: 0.5
  sub_metapth_act: leaky_relu
  submetapath_attention: False
  epochs: 50
  num_hop: 2
  run: 5

# -------model instance + dataset-------
SeHGNN_DBLP: &SeHGNN_DBLP
  <<: [*DBLP,*SeHGNN]
  model: SeHGNN
  path: DBLP_checkpoint.pt


SeHGNN_ACM: &SeHGNN_ACM
  <<: [*ACM,*SeHGNN]
  model: SeHGNN
  path: ACM_checkpoint.pt

SeHGNN_IMDB: &SeHGNN_IMDB
  <<: [*IMDB,*SeHGNN] 
  model: SeHGNN
  path: IMDB_checkpoint.pt

SeHGNN_Freebase: &SeHGNN_Freebase
  <<: [*Freebase,*SeHGNN]
  lr: 0.0003
  weight_decay: 0.0001
  model: SeHGNN
  path: Freebase_checkpoint.pt
  
# -------model instance (exist study)-------
SeHGNN_DBLP_tuned: &SeHGNN_DBLP_tuned
  <<: [*DBLP,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 3
  num_hop: 2
  num_label_hops: 4 
  label_feats: True
  residual: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  amp: True
  run: 5

  path: DBLP_checkpoint.pt


SeHGNN_ACM_tuned: &SeHGNN_ACM_tuned
  <<: [*ACM,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 1
  num_hop: 4
  num_label_hops: 4 
  label_feats: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  amp: True
  run: 5
  path: ACM_checkpoint.pt

SeHGNN_IMDB_tuned: &SeHGNN_IMDB_tuned
  <<: [*IMDB,*SeHGNN] 
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 4
  num_hop: 4
  num_label_hops: 4 
  label_feats: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.
  amp: True
  run: 5
  path: IMDB_checkpoint.pt

SeHGNN_Freebase_tuned: &SeHGNN_Freebase_tuned
  <<: [*Freebase,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 4
  num_hop: 2
  num_label_hops: 3
  label_feats: True
  residual: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  lr: 3e-5
  weight_decay: 3e-5
  batch_size: 256
  amp: True
  patience: 30 
  run: 5
  path: Freebase_checkpoint.pt

# -------model instance (our study)-------
#SeHGNN
SeHGNNver2_DBLP: &SeHGNNver2_DBLP
  # <<: [*DBLP,*SeHGNN]
  <<: *SeHGNN_DBLP_tuned
  model: SeHGNNver2
  n_fp_submetapath_layers: 2
  submetapath_hops: 4
  submetapath_feature_weight: 0.2
  sampling_limit: 10
  sub_metapth_act: leaky_relu
  submetapath_attention: True
  neighbor_aggr_mode: all
  path: DBLP_checkpoint.pt
SeHGNNver2_ACM: &SeHGNNver2_ACM
  # <<: [*ACM,*SeHGNN]
  <<: *SeHGNN_ACM_tuned
  model: SeHGNNver2
  n_fp_submetapath_layers: 2
  submetapath_hops: 4
  submetapath_feature_weight: 0.2
  sampling_limit: 8
  sub_metapth_act: leaky_relu
  submetapath_attention: True
  neighbor_aggr_mode: all
  path: ACM_checkpoint.pt
SeHGNNver2_IMDB: &SeHGNNver2_IMDB
  # <<: [*IMDB,*SeHGNN]
  <<: *SeHGNN_IMDB_tuned
  model: SeHGNNver2
  n_fp_submetapath_layers: 2
  submetapath_hops: 3
  submetapath_feature_weight: 0.2
  sampling_limit: 5
  sub_metapth_act: leaky_relu
  submetapath_attention: True
  neighbor_aggr_mode: all
  path: IMDB_checkpoint.pt
SeHGNNver2_Freebase: &SeHGNNver2_Freebase
  # <<: [*Freebase,*SeHGNN]
  <<: *SeHGNN_Freebase_tuned
  model: SeHGNNver2
  n_fp_submetapath_layers: 2
  lr: 0.0003
  submetapath_feature_weight: 0.2
  weight_decay: 0.0001
  sub_metapth_act: leaky_relu
  neighbor_aggr_mode: all
  path: Freebase_checkpoint.pt

# -------model instance (our study (exist tuned setting))-------
#SeHGNN
SeHGNNver2_DBLP_tuned: &SeHGNNver2_DBLP_tuned
  <<: *SeHGNNver2_DBLP
  num_hop: 3
  submetapath_hops: 3
  sampling_limit: 10


SeHGNNver2_ACM_tuned: &SeHGNNver2_ACM_tuned
  <<: *SeHGNN_ACM_tuned
  submetapath_hops: 4
  submetapath_feature_weight: 0.4
  sampling_limit: 20 

SeHGNNver2_IMDB_tuned: &SeHGNNver2_IMDB_tuned 
  <<: *SeHGNN_IMDB_tuned 
  submetapath_hops: 4
  sampling_limit: 15


#debag
debag:
 <<: *SeHGNNver2_ACM_tuned
 neighbor_aggr_mode: use_submetapath_for_semantic_fusion
#  model_name: SeHGNN
#  submetapath_feature_weight: 0.3
 label_feats: True
#  n_fp_submetapath_layers: 2
 act: none
 run: 5
 epochs: 50
 num_label_hops: 2
 num_hop: 2
 submetapath_hops: 2
 sub_metapth_act: leaky_relu
 submetapath_attention: True


defaults:
  - override hydra/sweeper: optuna # [basic, optuna]

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    n_jobs: 1
    n_trials: 50