key: debag
experiment_name: debag
tracking_uri: http://127.0.0.1:5000

## -------datasets (HeteroGraph)----
HeteroGraph: &HeteroGraph
 seeds: 42
 gpu: 0
 cpu: False
 root: ../data/

# -------datasets (HGB)-------------
DBLP: &DBLP
  <<: *HeteroGraph
  dataset: DBLP
  nclass: 4
  tgt_type: A

ACM: &ACM
  <<: *HeteroGraph
  dataset: ACM
  nclass: 3
  tgt_type: P
  ACM_keep_F: False

IMDB: &IMDB
  <<: *HeteroGraph
  dataset: IMDB
  nclass: 5
  tgt_type: M
  
Freebase: &Freebase
  <<: *HeteroGraph
  dataset: Freebase
  nclass: 7
  tgt_type: '0'

# -------model instance------------
SeHGNN: &SeHGNN
  model: SeHGNN
  embed_size: 256
  label_feats: False
  num_label_hops: 2
  n_fp_layers: 2
  n_task_layers: 3
  hidden: 512
  dropout: 0.5
  input_drop: 0.1
  att_drop: 0.
  act: none # ['none', 'relu', 'leaky_relu', 'sigmoid']
  residual: False
  amp: False
  lr: 0.001
  weight_decay: 0
  batch_size: 10000
  patience: 50
  num_heads: 1
  epochs: 50
  num_hop: 2
  run: 5
  gpu_id: 0

SeHGNNver2: &SeHGNNver2
  <<: *SeHGNN
  model: SeHGNNver2
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_manual
  submetapath_hops: 2
  submetapath_feature_weight: none
  sampling_limit: none

# -------model instance + dataset-------
SeHGNN_DBLP: &SeHGNN_DBLP
  <<: [*DBLP,*SeHGNN]
  model: SeHGNN
  path: DBLP_checkpoint.pt

SeHGNN_ACM: &SeHGNN_ACM
  <<: [*ACM,*SeHGNN]
  model: SeHGNN
  path: ACM_checkpoint.pt

SeHGNN_IMDB: &SeHGNN_IMDB
  <<: [*IMDB,*SeHGNN] 
  model: SeHGNN
  path: IMDB_checkpoint.pt

SeHGNN_Freebase: &SeHGNN_Freebase
  <<: [*Freebase,*SeHGNN]
  lr: 0.0003
  weight_decay: 0.0001
  model: SeHGNN
  path: Freebase_checkpoint.pt
  
# -------model instance (exist study)-------
SeHGNN_DBLP_tuned: &SeHGNN_DBLP_tuned
  <<: [*DBLP,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 3
  num_hop: 2
  num_label_hops: 4 
  label_feats: True
  residual: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  amp: True
  run: 5
  path: DBLP_checkpoint.pt

SeHGNN_ACM_tuned: &SeHGNN_ACM_tuned
  <<: [*ACM,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 1
  num_hop: 4
  num_label_hops: 4 
  label_feats: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  amp: True
  run: 5
  path: ACM_checkpoint.pt

SeHGNN_IMDB_tuned: &SeHGNN_IMDB_tuned
  <<: [*IMDB,*SeHGNN] 
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 4
  num_hop: 4
  num_label_hops: 4 
  label_feats: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.
  amp: True
  run: 5
  path: IMDB_checkpoint.pt

SeHGNN_Freebase_tuned: &SeHGNN_Freebase_tuned
  <<: [*Freebase,*SeHGNN]
  model: SeHGNN
  epochs: 200
  n_fp_layers: 2
  n_task_layers: 4
  num_hop: 2
  num_label_hops: 3
  label_feats: True
  residual: True
  hidden: 512
  embed_size: 512
  dropout: 0.5
  input_drop: 0.5
  lr: 3e-5
  weight_decay: 3e-5
  batch_size: 256
  amp: True
  patience: 30 
  run: 5
  path: Freebase_checkpoint.pt

# -------model instance (our study)-------
#SeHGNN
SeHGNNver2_DBLP: &SeHGNNver2_DBLP
  <<: [*SeHGNN_DBLP_tuned,*SeHGNNver2]
  model: SeHGNNver2
  path: DBLP_checkpoint.pt

SeHGNNver2_IMDB: &SeHGNNver2_IMDB
  <<: [*SeHGNN_IMDB_tuned,*SeHGNNver2]
  model: SeHGNNver2
  path: IMDB_checkpoint.pt

SeHGNNver2_ACM: &SeHGNNver2_ACM
  <<: [*SeHGNN_ACM_tuned,*SeHGNNver2]
  model: SeHGNNver2
  path: ACM_checkpoint.pt

# -------model instance (our study + tuned parameters)-------
#SeHGNN
SeHGNNver2_DBLP_tuned: &SeHGNNver2_DBLP_tuned
  <<: *SeHGNNver2_DBLP
  model: SeHGNNver2
  neighbor_aggr_calc: none
  neighbor_aggr_mode: none
  label_feats: True 
  amp: True
  epochs: 50
  submetapath_hops: 2
  dropout: 0.4
  embed_size: 512
  input_drop: 0.5
  lr: 0.001
  n_task_layers: 2
  weight_decay: 0
  run: 5
  path: DBLP_checkpoint.pt

SeHGNNver2_IMDB_tuned: &SeHGNNver2_IMDB_tuned
  <<: *SeHGNNver2_IMDB
  model: SeHGNNver2
  neighbor_aggr_calc: none
  neighbor_aggr_mode: none
  label_feats: True 
  amp: True
  epochs: 50
  submetapath_hops: 2
  dropout: 0.2
  embed_size: 512
  input_drop: 0
  lr: 0.001
  n_task_layers: 2
  weight_decay: 0
  run: 5
  path: IMDB_checkpoint.pt

SeHGNNver2_ACM_tuned: &SeHGNNver2_ACM_tuned
  <<: *SeHGNNver2_ACM
  model: SeHGNNver2
  neighbor_aggr_calc: none
  neighbor_aggr_mode: none
  label_feats: True 
  amp: True
  epochs: 50
  submetapath_hops: 2
  dropout: 0.5
  embed_size: 512
  input_drop: 0.5
  lr: 0.001
  n_task_layers: 3 
  weight_decay: 0.0005
  run: 5
  path: ACM_checkpoint.pt

# -------model instance (our study + instance model setting)-------
#basic
#DBLP
SeHGNNver2_DBLP_tuned_basic_alpha_manual: &SeHGNNver2_DBLP_tuned_basic_alpha_manual
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2

SeHGNNver2_DBLP_tuned_basic_alpha_auto: &SeHGNNver2_DBLP_tuned_basic_alpha_auto
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_auto


SeHGNNver2_DBLP_tuned_basic_transformer: &SeHGNNver2_DBLP_tuned_basic_transformer
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: transformer

#IMDB
SeHGNNver2_IMDB_tuned_basic_alpha_manual: &SeHGNNver2_IMDB_tuned_basic_alpha_manual 
  <<: *SeHGNNver2_IMDB_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2 

SeHGNNver2_IMDB_tuned_basic_alpha_auto: &SeHGNNver2_IMDB_tuned_basic_alpha_auto
  <<: *SeHGNNver2_IMDB_tuned 
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_auto

SeHGNNver2_IMDB_tuned_basic_transformer: &SeHGNNver2_IMDB_tuned_basic_transformer 
  <<: *SeHGNNver2_IMDB_tuned 
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: transformer

#ACM
SeHGNNver2_ACM_tuned_basic_alpha_manual: &SeHGNNver2_ACM_tuned_basic_alpha_manual
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2

SeHGNNver2_ACM_tuned_basic_alpha_auto: &SeHGNNver2_ACM_tuned_basic_alpha_auto
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: alpha_auto

SeHGNNver2_ACM_tuned_basic_transformer: &SeHGNNver2_ACM_tuned_basic_transformer
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: basic
  neighbor_aggr_mode: transformer

#concat
#DBLP
SeHGNNver2_DBLP_tuned_concat_alpha_manual: &SeHGNNver2_DBLP_tuned_concat_alpha_manual
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2
  sampling_limit: 10

SeHGNNver2_DBLP_tuned_concat_alpha_auto: &SeHGNNver2_DBLP_tuned_concat_alpha_auto
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_auto
  sampling_limit: 10


SeHGNNver2_DBLP_tuned_concat_transformer: &SeHGNNver2_DBLP_tuned_3_concattransformer
  <<: *SeHGNNver2_DBLP_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: transformer
  sampling_limit: 10

#IMDB
SeHGNNver2_IMDB_tuned_concat_alpha_manual: &SeHGNNver2_IMDB_tuned_1_concat_alpha_manual
  <<: *SeHGNNver2_IMDB_tuned 
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2
  sampling_limit: 5

SeHGNNver2_IMDB_tuned_concat_alpha_auto: &SeHGNNver2_IMDB_tuned_1_concat_alpha_auto
  <<: *SeHGNNver2_IMDB_tuned 
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_auto
  sampling_limit: 5

SeHGNNver2_IMDB_tuned_concat_transformer: &SeHGNNver2_IMDB_tuned_concat_transformer
  <<: *SeHGNNver2_IMDB_tuned 
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: transformer
  sampling_limit: 5

#ACM
SeHGNNver2_ACM_tuned_concat_alpha_manual: &SeHGNNver2_ACM_tuned_concat_alpha_manual
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_manual
  submetapath_feature_weight: 0.2
  sampling_limit: 8

SeHGNNver2_ACM_tuned_concat_alpha_auto: &SeHGNNver2_ACM_tuned_concat_alpha_auto
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: alpha_auto
  sampling_limit: 8

SeHGNNver2_ACM_tuned_concat_transformer: &SeHGNNver2_ACM_tuned_concat_transformer
  <<: *SeHGNNver2_ACM_tuned
  neighbor_aggr_calc: concat
  neighbor_aggr_mode: transformer
  sampling_limit: 8




#debag
debag:
 <<: *SeHGNNver2_IMDB_tuned_basic_alpha_manual
 neighbor_aggr_calc: basic
 neighbor_aggr_mode: alpha_manual
 epochs: 5
 run: 1

defaults:
  - override hydra/sweeper: optuna # [basic, optuna]

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    n_jobs: 1
    n_trials: 50